### ISSUE TITLE
Readiness failing - 'code_style' errors for /auth/login

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform-control-panel#336]
The logs for cpanel are flooded with these errors:
```
2018-09-13 10:45:32,267 django.template DEBUG Exception while resolving variable 'code_style' in template 'rest_framework/login.html'.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/usr/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'code_style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'code_style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'code_style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [code_style] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fd937388488>>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7fd9373f9158>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fd93723c668>, 'STATIC_URL': '/static/', 'TIME_ZONE': 'UTC'}, {}, {'form': <AuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'view': <django.contrib.auth.views.LoginView object at 0x7fd93722da20>, 'next': '', 'site': <django.contrib.sites.requests.RequestSite object at 0x7fd93723cac8>, 'site_name': '100.122.14.82:8000'}, {'block': <Block Node: head. Contents: [<TextNode: '\n\n      '>, <Block Node: meta. Contents: [<TextNode: '\n        <meta http-equiv'>]>, <TextNode: '\n\n      <title>'>, <Block Node: title. Contents: [<IfNode>, <TextNode: 'Django REST framework'>]>, <TextNode: '</title>\n\n      '>, <Block Node: style. Contents: [<TextNode: '\n        '>, <Block Node: bootstrap_theme. Contents: [<TextNode: '\n          <link rel="sty'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbda0>, <TextNode: '"/>\n          <link rel="'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbe48>, <TextNode: '"/>\n        '>]>, <TextNode: '\n\n        <link rel="styl'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbeb8>, <TextNode: '"/>\n        <link rel="st'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbf60>, <TextNode: '"/>\n        '>, <IfNode>, <TextNode: '\n      '>]>, <TextNode: '\n\n    '>]>}, {'block': <Block Node: style. Contents: [<TextNode: '\n        '>, <Block Node: bootstrap_theme. Contents: [<TextNode: '\n          <link rel="sty'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbda0>, <TextNode: '"/>\n          <link rel="'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbe48>, <TextNode: '"/>\n        '>]>, <TextNode: '\n\n        <link rel="styl'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbeb8>, <TextNode: '"/>\n        <link rel="st'>, <django.templatetags.static.StaticNode object at 0x7fd9372bbf60>, <TextNode: '"/>\n        '>, <IfNode>, <TextNode: '\n      '>]>}]
```

This occurs every 5 seconds, suggesting the readiness probe, which is configured:
```
    Readiness:  http-get http://:http/auth/login delay=5s timeout=1s period=5s #success=1 #failure=3
```

And sure enough, the readiness is failing:
```
Events:
  Type     Reason     Age                From                                                   Message
  ----     ------     ----               ----                                                   -------
  Warning  Unhealthy  58m (x20 over 1h)  kubelet, ip-192-168-14-128.eu-west-1.compute.internal  Readiness probe failed: Get http://100.101.194.119:8000/auth/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by davidread** [comment]
Could be related:
> django rest framework stopped bundling some deps for the friendly human interface to the api docs
